export type IconNames =
  | 'ActivityDoType'
  | 'ActivityReadType'
  | 'ActivityWatchType'
  | 'ArrowLeft'
  | 'Checkbox'
  | 'InlineLoader'
  | 'PieChart'
  | 'Goal'
  | 'Google'
  | 'Activities'
  | 'Silver'
  | 'Dodayman'
  | 'Duration'
  | 'Flag'
  | 'Score'
  | 'Pin';
