export type IconNames = 'Checkbox'
  | 'DoubleChevron'
  | 'InlineLoader'
  | 'TodayCalendar'
  | 'Lighting'
  | 'FolderPlus'
  | 'CheckboxInBox'
  | 'ArrowLeft'
  | 'ArrowRight'
  | 'Apps'
  | 'CloseCircle'
  | 'Close';